### PR TITLE
dev > prod

### PR DESCRIPTION
**Pull request by spaghettimaster**

### CODE REVIEW

**Comment by JedMeister** [comment]
Hey @spaghettimaster apologies on such slow turnaround on this...

I just had a quick look and noticed that the systemd service file also sets ["NODE_ENV=development"](https://github.com/turnkeylinux-apps/ghost/blob/master/overlay/etc/systemd/system/ghost_blog.service#L8). Was that an oversight? Or is that as intended?

**Comment by spaghettimaster** [comment]
I forgot to remove this file.

This systemd service was needed for the local installation.

**Comment by JedMeister** [comment]
Hey @spaghettimaster - Apologies on slow turnaround on this one... So this should be ready to merge now right?

**Comment by spaghettimaster** [comment]
Yes, it's ready now.

**Pull request merged**
